(*
    This file is part of Delphi-OpenCV-Class project.
    https://github.com/Laex/Delphi-OpenCV-Class

    It is subject to the license terms in the LICENSE file found in the top-level directory
    of this distribution and at https://www.apache.org/licenses/LICENSE-2.0.txt

    Copyright 2021, Laentir Valetov, laex@bk.ru

    Licensed under the Apache License, Version 2.0 (the 'License');
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an 'AS IS' BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*)

{$IFDEF INTERFACE}

{$if not defined(OPENCV_CALIB3D_HPP)}
{$define OPENCV_CALIB3D_HPP}

{$IFEND OPENCV_CALIB3D_HPP}

{$ENDIF INTERFACE}

// ===========================================================================

{$IFDEF IMPLEMENTATION}


{$if defined(OPENCV_CALIB3D_HPP) an (not defined(OPENCV_CALIB3D_HPP_IMPL))}
{$define OPENCV_CALIB3D_HPP_IMPL}

{$IFEND OPENCV_CALIB3D_HPP}

{$ENDIF IMPLEMENTATION}
