{
  2979
  ??Scv@@YA?AVMatExpr@0@AEBVMat@0@@Z
  class cv::MatExpr cv::operator~(class cv::Mat const &)
}
 function MatExpr_LogicalNot_Mat(Obj: pMatExpr; m: pMat): pMatExpr;//
//procedure MatExpr_LogicalNot_Mat(Obj: pMatExpr; m: pMat); //
  external opencv_world_dll                               //
  name '??Scv@@YA?AVMatExpr@0@AEBVMat@0@@Z'               //
{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
{
  2860
  ??Gcv@@YA?AVMatExpr@0@AEBVMat@0@AEBV?$Scalar_@N@0@@Z
  class cv::MatExpr cv::operator-(class cv::Mat const &,class cv::Scalar_<double> const &)
}
function MatExpr_Subtract_Mat_MatExpr(Obj: pMatExpr; m: pMat; s: pScalar): pMatExpr; external opencv_world_dll //
  name '??Gcv@@YA?AVMatExpr@0@AEBVMat@0@AEBV?$Scalar_@N@0@@Z'
{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
