// ??0Scalar@own@gapi@cv@@QEAA@N@Z
// public: __cdecl cv::gapi::own::Scalar::Scalar(double) __ptr64
procedure constructor_Scalar(Obj: pScalar; v0: double); overload; external opencv_world_dll index 1071 {$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
// ??0Scalar@own@gapi@cv@@QEAA@NNNN@Z
// public: __cdecl cv::gapi::own::Scalar::Scalar(double,double,double,double) __ptr64
procedure constructor_Scalar(Obj: pScalar; v0, v1, v2, v3: double); overload; external opencv_world_dll index 1072 {$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
// ??0Scalar@own@gapi@cv@@QEAA@XZ
// public: __cdecl cv::gapi::own::Scalar::Scalar(void) __ptr64
procedure constructor_Scalar(Obj: pScalar); overload; external opencv_world_dll index 1073 {$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
// ??4Scalar@own@gapi@cv@@QEAAAEAV0123@$$QEAV0123@@Z	public: class cv::gapi::own::Scalar & __ptr64 __cdecl cv::gapi::own::Scalar::operator=(class cv::gapi::own::Scalar && __ptr64) __ptr64
// ??4Scalar@own@gapi@cv@@QEAAAEAV0123@AEBV0123@@Z	public: class cv::gapi::own::Scalar & __ptr64 __cdecl cv::gapi::own::Scalar::operator=(class cv::gapi::own::Scalar const & __ptr64) __ptr64
// ?all@Scalar@own@gapi@cv@@SA?AV1234@N@Z	public: static class cv::gapi::own::Scalar __cdecl cv::gapi::own::Scalar::all(double)
