// -------------- DISOpticalFlow --------------
// ??0DISOpticalFlow@cv@@QEAA@$$QEAV01@@Z;public: __cdecl cv::DISOpticalFlow::DISOpticalFlow(class cv::DISOpticalFlow && __ptr64) __ptr64
// ??0DISOpticalFlow@cv@@QEAA@AEBV01@@Z;public: __cdecl cv::DISOpticalFlow::DISOpticalFlow(class cv::DISOpticalFlow const & __ptr64) __ptr64
// ??0DISOpticalFlow@cv@@QEAA@XZ;public: __cdecl cv::DISOpticalFlow::DISOpticalFlow(void) __ptr64
{
  ??1DISOpticalFlow@cv@@UEAA@XZ
  public: virtual __cdecl cv::DISOpticalFlow::~DISOpticalFlow(void) __ptr64
}
procedure Destructor_DISOpticalFlow(obj: pDISOpticalFlow); external opencv_world_dll name '??1DISOpticalFlow@cv@@UEAA@XZ'{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
// ??4DISOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z;public: class cv::DISOpticalFlow & __ptr64 __cdecl cv::DISOpticalFlow::operator=(class cv::DISOpticalFlow && __ptr64) __ptr64
// ??4DISOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z;public: class cv::DISOpticalFlow & __ptr64 __cdecl cv::DISOpticalFlow::operator=(class cv::DISOpticalFlow const & __ptr64) __ptr64
// ??_7DISOpticalFlow@cv@@6B@;const cv::DISOpticalFlow::`vftable'
{
  ?create@DISOpticalFlow@cv@@SA?AU?$Ptr@VDISOpticalFlow@cv@@@2@H@Z
  public: static struct cv::Ptr<class cv::DISOpticalFlow> __cdecl cv::DISOpticalFlow::create(int)
}
procedure create_DISOpticalFlow(obj: pPointer; preset: Int); external opencv_world_dll name '?create@DISOpticalFlow@cv@@SA?AU?$Ptr@VDISOpticalFlow@cv@@@2@H@Z'{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};

// -------------- DenseOpticalFlow --------------
// ??0DenseOpticalFlow@cv@@QEAA@$$QEAV01@@Z	??0DenseOpticalFlow@cv@@QEAA@$$QEAV01@@Z	cv::DenseOpticalFlow::DenseOpticalFlow(class cv::DenseOpticalFlow &&)
// ??0DenseOpticalFlow@cv@@QEAA@AEBV01@@Z	??0DenseOpticalFlow@cv@@QEAA@AEBV01@@Z	cv::DenseOpticalFlow::DenseOpticalFlow(class cv::DenseOpticalFlow const &)
// ??0DenseOpticalFlow@cv@@QEAA@XZ	??0DenseOpticalFlow@cv@@QEAA@XZ	cv::DenseOpticalFlow::DenseOpticalFlow(void)
{
  ??1DenseOpticalFlow@cv@@UEAA@XZ
  ??1DenseOpticalFlow@cv@@UEAA@XZ
  cv::DenseOpticalFlow::~DenseOpticalFlow(void)
}
procedure Destructor_DenseOpticalFlow(obj: pDenseOpticalFlow); external opencv_world_dll name '??1DenseOpticalFlow@cv@@UEAA@XZ'{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};

// ??4DenseOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	??4DenseOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	class cv::DenseOpticalFlow & cv::DenseOpticalFlow::operator=(class cv::DenseOpticalFlow &&)
// ??4DenseOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	??4DenseOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	class cv::DenseOpticalFlow & cv::DenseOpticalFlow::operator=(class cv::DenseOpticalFlow const &)
{
  ??_7DenseOpticalFlow@cv@@6B@
  ??_7DenseOpticalFlow@cv@@6B@
  const cv::DenseOpticalFlow::`vftable'
}
// procedure vftable_DenseOpticalFlow; external opencv_world_dll name '??_7DenseOpticalFlow@cv@@6B@'{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};

// -------------- FarnebackOpticalFlow --------------
// ??0FarnebackOpticalFlow@cv@@QEAA@$$QEAV01@@Z	??0FarnebackOpticalFlow@cv@@QEAA@$$QEAV01@@Z	cv::FarnebackOpticalFlow::FarnebackOpticalFlow(class cv::FarnebackOpticalFlow &&)
// ??0FarnebackOpticalFlow@cv@@QEAA@AEBV01@@Z	??0FarnebackOpticalFlow@cv@@QEAA@AEBV01@@Z	cv::FarnebackOpticalFlow::FarnebackOpticalFlow(class cv::FarnebackOpticalFlow const &)
// ??0FarnebackOpticalFlow@cv@@QEAA@XZ	??0FarnebackOpticalFlow@cv@@QEAA@XZ	cv::FarnebackOpticalFlow::FarnebackOpticalFlow(void)
// ??1FarnebackOpticalFlow@cv@@UEAA@XZ	??1FarnebackOpticalFlow@cv@@UEAA@XZ	cv::FarnebackOpticalFlow::~FarnebackOpticalFlow(void)
// ??4FarnebackOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	??4FarnebackOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	class cv::FarnebackOpticalFlow & cv::FarnebackOpticalFlow::operator=(class cv::FarnebackOpticalFlow &&)
// ??4FarnebackOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	??4FarnebackOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	class cv::FarnebackOpticalFlow & cv::FarnebackOpticalFlow::operator=(class cv::FarnebackOpticalFlow const &)
// ??_7FarnebackOpticalFlow@cv@@6B@	??_7FarnebackOpticalFlow@cv@@6B@	const cv::FarnebackOpticalFlow::`vftable'
// ?create@FarnebackOpticalFlow@cv@@SA?AU?$Ptr@VFarnebackOpticalFlow@cv@@@2@HN_NHHHNH@Z	?create@FarnebackOpticalFlow@cv@@SA?AU?$Ptr@VFarnebackOpticalFlow@cv@@@2@HN_NHHHNH@Z	struct cv::Ptr<class cv::FarnebackOpticalFlow> cv::FarnebackOpticalFlow::create(int,double,bool,int,int,int,double,int)

// -------------- SparseOpticalFlow --------------
// ??0SparseOpticalFlow@cv@@QEAA@$$QEAV01@@Z	??0SparseOpticalFlow@cv@@QEAA@$$QEAV01@@Z	cv::SparseOpticalFlow::SparseOpticalFlow(class cv::SparseOpticalFlow &&)
// ??0SparseOpticalFlow@cv@@QEAA@AEBV01@@Z	??0SparseOpticalFlow@cv@@QEAA@AEBV01@@Z	cv::SparseOpticalFlow::SparseOpticalFlow(class cv::SparseOpticalFlow const &)
// ??0SparseOpticalFlow@cv@@QEAA@XZ	??0SparseOpticalFlow@cv@@QEAA@XZ	cv::SparseOpticalFlow::SparseOpticalFlow(void)
// ??1SparseOpticalFlow@cv@@UEAA@XZ	??1SparseOpticalFlow@cv@@UEAA@XZ	cv::SparseOpticalFlow::~SparseOpticalFlow(void)
// ??4SparseOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	??4SparseOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	class cv::SparseOpticalFlow & cv::SparseOpticalFlow::operator=(class cv::SparseOpticalFlow &&)
// ??4SparseOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	??4SparseOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	class cv::SparseOpticalFlow & cv::SparseOpticalFlow::operator=(class cv::SparseOpticalFlow const &)
// ??_7SparseOpticalFlow@cv@@6B@	??_7SparseOpticalFlow@cv@@6B@	const cv::SparseOpticalFlow::`vftable'

// ??0SparsePyrLKOpticalFlow@cv@@QEAA@$$QEAV01@@Z	??0SparsePyrLKOpticalFlow@cv@@QEAA@$$QEAV01@@Z	cv::SparsePyrLKOpticalFlow::SparsePyrLKOpticalFlow(class cv::SparsePyrLKOpticalFlow &&)
// ??0SparsePyrLKOpticalFlow@cv@@QEAA@AEBV01@@Z	??0SparsePyrLKOpticalFlow@cv@@QEAA@AEBV01@@Z	cv::SparsePyrLKOpticalFlow::SparsePyrLKOpticalFlow(class cv::SparsePyrLKOpticalFlow const &)
// ??0SparsePyrLKOpticalFlow@cv@@QEAA@XZ	??0SparsePyrLKOpticalFlow@cv@@QEAA@XZ	cv::SparsePyrLKOpticalFlow::SparsePyrLKOpticalFlow(void)
// ??1SparsePyrLKOpticalFlow@cv@@UEAA@XZ	??1SparsePyrLKOpticalFlow@cv@@UEAA@XZ	cv::SparsePyrLKOpticalFlow::~SparsePyrLKOpticalFlow(void)
// ??4SparsePyrLKOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	??4SparsePyrLKOpticalFlow@cv@@QEAAAEAV01@$$QEAV01@@Z	class cv::SparsePyrLKOpticalFlow & cv::SparsePyrLKOpticalFlow::operator=(class cv::SparsePyrLKOpticalFlow &&)
// ??4SparsePyrLKOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	??4SparsePyrLKOpticalFlow@cv@@QEAAAEAV01@AEBV01@@Z	class cv::SparsePyrLKOpticalFlow & cv::SparsePyrLKOpticalFlow::operator=(class cv::SparsePyrLKOpticalFlow const &)
// ??_7SparsePyrLKOpticalFlow@cv@@6B@	??_7SparsePyrLKOpticalFlow@cv@@6B@	const cv::SparsePyrLKOpticalFlow::`vftable'
// ?create@SparsePyrLKOpticalFlow@cv@@SA?AU?$Ptr@VSparsePyrLKOpticalFlow@cv@@@2@V?$Size_@H@2@HVTermCriteria@2@HN@Z	?create@SparsePyrLKOpticalFlow@cv@@SA?AU?$Ptr@VSparsePyrLKOpticalFlow@cv@@@2@V?$Size_@H@2@HVTermCriteria@2@HN@Z	struct cv::Ptr<class cv::SparsePyrLKOpticalFlow> cv::SparsePyrLKOpticalFlow::create(class cv::Size_<int>,int,class cv::TermCriteria,int,double)
