// ??0MatSize@cv@@QEAA@PEAH@Z      public: __cdecl cv::MatSize::MatSize(int * __ptr64) __ptr64
// ??4MatSize@cv@@QEAAAEAU01@$$QEAU01@@Z   public: struct cv::MatSize & __ptr64 __cdecl cv::MatSize::operator=(struct cv::MatSize && __ptr64) __ptr64
// ??4MatSize@cv@@QEAAAEAU01@AEBU01@@Z     public: struct cv::MatSize & __ptr64 __cdecl cv::MatSize::operator=(struct cv::MatSize const & __ptr64) __ptr64
// ??RMatSize@cv@@QEBA?AV?$Size_@H@1@XZ
// public: class cv::Size_<int> __cdecl cv::MatSize::operator()(void)const __ptr64
procedure operator_MatSize_MatSizeToSize(Obj: pMatSize; const s: TSize); external opencv_world_dll
//index 2965
name '??RMatSize@cv@@QEBA?AV?$Size_@H@1@XZ'
{$IFDEF DELAYED_LOAD_DLL} delayed{$ENDIF};
// ?dims@MatSize@cv@@QEBAHXZ       public: int __cdecl cv::MatSize::dims(void)const __ptr64
